
//
// generated by xrescode on 2019-06-06 22:37:19, please don't edit it
//

#ifndef CONFIG_EXCEL_CONFIG_SET_FAGAME_CONFIG_SET_FAMAPINFO_H
#define CONFIG_EXCEL_CONFIG_SET_FAGAME_CONFIG_SET_FAMAPINFO_H

#pragma once

#include <stdint.h>
#include <cstddef>
#include <functional>
#include <vector>
#include <string>
#include <map>

#include <std/smart_ptr.h>

#include <lock/spin_rw_lock.h>

#include <config/compiler_features.h>
#include <design_pattern/singleton.h>
#include <log/log_wrapper.h>

#include <config/fa_gamemap.pb.h>

namespace excel {
    class config_set_FaMapInfo {
    public:
        typedef FaGame::FaMapInfo item_type;
        typedef FaGame::FaMapInfo proto_type;
        typedef std::shared_ptr<item_type> item_ptr_type;

    public:
        config_set_FaMapInfo();
        ~config_set_FaMapInfo();

        int on_inited();

        int load_all();

        void clear();

    private:
        int load_file(const char*, size_t);

        int load_list(const char*);

        void merge_data(std::std::shared_ptr<item_type>);

        // index: Id
public:
        typedef item_ptr_type Id_value_type;
        Id_value_type get_by_Id(int32_t Id);

private:
        std::map<std::tuple<int32_t>, Id_value_type> Id_data_;

    };
}

#endif // CONFIG_EXCEL_CONFIG_SET_FAGAME_CONFIG_SET_FAMAPINFO_H
