# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xrescode_extensions_v3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cxrescode_extensions_v3.proto\x12\x08xrescode\x1a google/protobuf/descriptor.proto\"\x90\x01\n\x0exrescode_index\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x03(\t\x12\x31\n\nindex_type\x18\x03 \x01(\x0e\x32\x1d.xrescode.xrescode_index_type\x12\x14\n\x0c\x66ile_mapping\x18\x04 \x01(\t\x12\x17\n\x0f\x61llow_not_found\x18\x05 \x01(\x08\"\x9b\x01\n\x0fxrescode_loader\x12\x11\n\tfile_list\x18\x65 \x01(\t\x12\x11\n\tfile_path\x18\x66 \x01(\t\x12\x12\n\ncode_field\x18g \x01(\t\x12*\n\x07indexes\x18\xc9\x01 \x03(\x0b\x32\x18.xrescode.xrescode_index\x12\r\n\x04tags\x18\xad\x02 \x03(\t\x12\x13\n\nclass_name\x18\x91\x03 \x01(\t*Y\n\x13xrescode_index_type\x12\x0f\n\x0b\x45N_INDEX_KV\x10\x00\x12\x0f\n\x0b\x45N_INDEX_KL\x10\x01\x12\x0f\n\x0b\x45N_INDEX_IV\x10\x02\x12\x0f\n\x0b\x45N_INDEX_IL\x10\x03:K\n\x06loader\x12\x1f.google.protobuf.MessageOptions\x18\xc7\n \x03(\x0b\x32\x19.xrescode.xrescode_loaderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xrescode_extensions_v3_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(loader)

  DESCRIPTOR._options = None
  _XRESCODE_INDEX_TYPE._serialized_start=381
  _XRESCODE_INDEX_TYPE._serialized_end=470
  _XRESCODE_INDEX._serialized_start=77
  _XRESCODE_INDEX._serialized_end=221
  _XRESCODE_LOADER._serialized_start=224
  _XRESCODE_LOADER._serialized_end=379
# @@protoc_insertion_point(module_scope)
